name: PiggyShopUI
main: DaPigGuy\PiggyShopUI\PiggyShopUI
version: 2.0.1
api: 3.2.0
load: POSTWORLD
author: DaPigGuy
softdepend: ["EconomyAPI"]
website: "https://github.com/DaPigGuy/PiggyShopUI/"
permissions:
  piggyshopui:
    default: false
    description: "Use everything in PiggyShopUI"
    children:
      piggyshopui.command:
        default: op
        description: "Use all PiggyShopUI commands"
        children:
          piggyshopui.command.shop:
            default: op
            description: "Use /shop"
            children:
              piggyshopui.command.shop.use:
                default: true
                description: "Use /shop"
              piggyshopui.command.shop.edit:
                default: op
                description: "Use /shop edit"
